name: Regressio Tests


on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - pre-prod
      tags:
        description: "Select test tags (eg dms). leave blank to run all tests"
        required: false
        default: ""

jobs:
  regression-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Decrypt Secrets
        uses: ministryofjustice/modernisation-platform-github-actions/decrypt-secrets@3f9fb1af00462c69c806640652ddf41292963615 # v3.2.5
        with:
          environment_management: ${{ needs.fetch-secrets.outputs.environment_management }}
          github_ci_user_environments_repo_pat: ${{ needs.fetch-secrets.outputs.github_ci_user_environments_repo_pat }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Set Environment Variables
        run: |
          echo "GITHUB_TOKEN=$GITHUB_CI_USER_ENVIRONMENTS_REPO_PAT" >> $GITHUB_ENV

      - name: Get AWS Account Number
        run: |
          ACCOUNT_NUMBER=$(jq -r -e --arg account_name "${ACCOUNT_NAME}" '.account_ids[$account_name]' <<< $ENVIRONMENT_MANAGEMENT)
          echo "::add-mask::$ACCOUNT_NUMBER"
          echo "ACCOUNT_NUMBER=${ACCOUNT_NUMBER}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df  # v4.2.1
        with:
          role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions"
          role-session-name: githubactionsrolesession
          aws-region: "eu-west-2"
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install uv
        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5.4.0
        with:
          version: "latest"
          python-version: "3.12"

      - name: Install Requirements
        run: |
          uv sync
      
      - name: Run Regression Tests
        env: 
          ENV_NAME: ${{ github.event.inputs.environment  }}
        run: |
          if [  -n "${{ github.event.inputs.tags }}" ]; then
            uv run pytest -m "${{ github.event.inputs.tags }}" --cucumberjson=report.json -vv
          else
            uv run pytest --cucumberjson=report.json -vv

      - name: Upload Test Report to Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Test Report
          path: report.json
